=== Shawnzu/Glance-MusicStore/Development/catalog_19031620.dtd
<!ELEMENT Musicstore (store_detail, music)>
<!--Declaring the root element first-->
<!ATTLIST Musicstore xmlns:xs CDATA #REQUIRED>
<!ATTLIST Musicstore xs:noNamespaceSchemaLocation CDATA #REQUIRED>
<!--Declaring the attributes of namespace xs which contains the XSD location-->
<!ELEMENT store_detail (Name,Info,Address,Contact,Website_address,Email)>
<!--Declaring store_detail element with 6 child elements-->
<!ATTLIST store_detail store_id CDATA #REQUIRED>
<!--Declaring the attribute of store_detail store_id which has character data and it mandatory to define it-->
<!ATTLIST Name logo CDATA #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!--Declaring parsed character data in element Name-->
<!ELEMENT Info (#PCDATA)>
<!ELEMENT Address (Street,City,Country)>
<!--Declaring Address element with 3 child elements-->
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT Contact (Telephone_No,Phone_No)>
<!--Declaring Contact element with 2 child elements-->
<!ELEMENT Telephone_No (#PCDATA)>
<!ELEMENT Phone_No (#PCDATA)>
<!ELEMENT Website_address (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT music (Song+)>
<!ELEMENT Song (#PCDATA|Title|Album_name|Singer|Label|Writers|Lyricist|Producers|Director|Release_year|Price)*>
<!--Declaring the mixed content where the Song element can contain zero or more occurrence of parsed character of data and other 10 elements-->
<!ATTLIST Song category (Jazz | Pop | Rock | Country | Dubstep) #REQUIRED>
<!--Declaring the attribute category of Song element which can either have any 5 of the given values and is mandatory to include any one of them-->
<!ATTLIST Song id ID #REQUIRED>
<!--Declaring the attribute id which must have an ID type in Song element-->
<!ELEMENT Title (#PCDATA)>
<!ATTLIST Title recorded CDATA #IMPLIED>
<!--Declaring the attribute recorded which can have character data and it is optional to define the attribute Title-->
<!ELEMENT Album_name (#PCDATA)>
<!ELEMENT Singer (#PCDATA)>
<!ATTLIST Singer performed_by CDATA #REQUIRED>
<!ELEMENT Label (#PCDATA)>
<!ELEMENT Writers (Writer+)>
<!--Declaring the element Writers where it must contain 1 or multiple child element Writer-->
<!ATTLIST Writers no_of_writer CDATA #REQUIRED>
<!ELEMENT Writer (#PCDATA)>
<!ELEMENT Lyricist (#PCDATA)>
<!ELEMENT Producers (Producer+)>
<!--Declaring the element Producers where it must contain 1 or multiple child element Producer-->
<!ATTLIST Producers no_of_producer CDATA #REQUIRED>
<!ELEMENT Producer (#PCDATA)>
<!ELEMENT Director (#PCDATA)>
<!ELEMENT Release_year (#PCDATA)>
<!ELEMENT Price (#PCDATA)>

=== Shawnzu/Glance-MusicStore/Development/catalog_19031620.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="catalog_19031620.css"?>
<!-- Linking the CSS file-->
<!DOCTYPE Musicstore SYSTEM "catalog_19031620.dtd">
<!-- Linking external DTD file-->
<Musicstore xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="catalog_19031620.xsd">
<!-- Linking the Schema file-->
<!-- Making Musicstore root element -->
    <store_detail store_id="0281">
    <!-- Defining child element of Musicstore -->
        <Name logo="Glaze">Glaze Music Store</Name>
        <Info>
        <![CDATA[
        Welcome to the Glaze's Music Store. We provide CDs and DVDs of songs of different Genres like Pop, Jazz, Rock, Country Music & Dubstep in a affortable price.
        ]]>
        <!-- Defining character data -->
        </Info>
        <Address>
            <Street>Location: New Road,</Street>
            <City>Kathmandu,</City>
            <Country>Nepal</Country>
        </Address>
        <Contact>
        <Telephone_No>Contact: 071-544281,</Telephone_No>
        <Phone_No>9847823223</Phone_No>
        </Contact>
        <Website_address>Visit: www.GlazeMusicStore.com</Website_address>
        <Email>Email: GlazeMusic@gmail.com</Email>
    </store_detail>

    <music>
    <!-- Defining child element of Musicstore -->
        <Song category="Jazz" id="JQT1">
        <!-- Defining child element of music with two attributes-->
            <Title>Quick Trick</Title>
            <Album_name>Album: Just Coolin</Album_name>
            <Singer performed_by="Band">By: Art Blakery &amp; The Jazz Messengers</Singer>Written By:
            <!-- defining character reference of & -->
            <Writers no_of_writer="1">
                <Writer>Bobby Timmons</Writer>
            </Writers>Produced By:
            <Producers no_of_producer="2">
                <Producer>Alfred Lion</Producer>
                <Producer>Zev Feldman</Producer>
            </Producers>Release Year:
            <Release_year> 2020</Release_year>
            <Price>Price: Rs200</Price>
        </Song>
        <Song category="Jazz" id="JBM2">
            <Title>Blue Moon</Title>
            <Singer performed_by="Solo">By: Billie Holiday</Singer>Written By:
            <Writers no_of_writer="2">
                <Writer>Billie Holiday</Writer>
                <Writer>Richard Rodgers</Writer>
            </Writers>
            <Lyricist>Lyricist: Lorenz Hertz</Lyricist>Produced By:
            <Producers no_of_producer="1">
                <Producer>Norman Granz</Producer>
            </Producers>Release Year:
            <Release_year> 1934</Release_year>
            <Price>Price: Rs200</Price>
        </Song>
        <Song category="Rock" id="RST3">
            <Title>Smells Like Teen Spirit</Title>
            <Album_name>Album: Nevermind (Deluxe Edition)</Album_name>
            <Singer performed_by="Band">By: Nirvana</Singer>
            <Label>Label: DGC</Label>Written By:
            <Writers no_of_writer="3">
                <Writer>Dave Grohl</Writer>
                <Writer>Krist Noveoselic</Writer>
                <Writer>Kurt Cobain</Writer>
            </Writers>Produced By:
            <Producers no_of_producer="1">
                <Producer>Butch Vig</Producer>
            </Producers>Release Year:
            <Release_year> 2020</Release_year>
            <Price>Price: Rs300</Price>
        </Song>
        <Song category="Rock" id="RWJ4">
            <Title>Welcome to the Jungle</Title>
            <Album_name>Album: Appetite for Destruction</Album_name>
            <Singer performed_by="Band">By: Guns N&apos; Roses</Singer>
            <!-- defining character reference of " ' " -->
            <Label>Label: Geffen</Label>Written By:
            <Writers no_of_writer="1">
                <Writer>Guns N&apos; Roses</Writer>
            </Writers>Produced By:
            <Producers no_of_producer="1">
                <Producer>Mike Clink</Producer>
            </Producers>Release year:
            <Release_year>1987</Release_year>
            <Price>Price: Rs320</Price>
        </Song>
        <Song category="Rock" id="RCS5">
            <Title recorded="Cello Studios">Chop Suey</Title>
            <Album_name>Album: Toxicity</Album_name>
            <Singer performed_by="Band">By: System of A Down</Singer>
            <Label>Label: Geffen</Label>Written By:
            <Writers no_of_writer="2">
                <Writer>Daron Malakian</Writer>
                <Writer>Serj Tankian</Writer>
            </Writers>Produced By:
            <Producers no_of_producer="2">
                <Producer>Rick Rubin</Producer>
                <Producer>Daron Malakian</Producer>
            </Producers>Release year:
            <Release_year>2001</Release_year>
            <Price>Price: Rs250</Price>
        </Song>
        <Song category="Rock" id="RBD6">
            <Title>Boulevard of Broken Dreams</Title>
            <Album_name>Album: American Idiot</Album_name>
            <Singer performed_by="Band">By: Green Day</Singer>
            <Label>Label: Reprise, Warner Bros.</Label>Written By:
            <Writers no_of_writer="3">
                <Writer>Billie Joe Armstrong</Writer>
                <Writer>Mike Dirnt</Writer>
                <Writer>Tre Cool</Writer>
            </Writers>Produced By:
            <Producers no_of_producer="2">
                <Producer>Rob Cavallo</Producer>
                <Producer>Green Day</Producer>
            </Producers>
            <Price>Price: Rs320</Price>
        </Song>
        <Song category="Country" id="CBH7">
            <Title>Beer Never Broke My Heart</Title>
            <Album_name>Album: What You See Is What You Get</Album_name>
            <Singer performed_by="Band">By: Luke Combs</Singer>
            <Label>Label: Columbia Nashville</Label>Written By:
            <Writers no_of_writer="3">
                <Writer>Luke Combs</Writer>
                <Writer>Randy Montana</Writer>
                <Writer>Jonathan Singleton</Writer>
            </Writers>Produced By:
            <Producers no_of_producer="1">
                <Producer>Scott Moffatt</Producer>
            </Producers>Release Year:
            <Release_year> 2019</Release_year>
            <Price>Price: Rs180</Price>
        </Song>
        <Song category="Country" id="CGC8">
            <Title recorded="American country music">God's Country</Title>
            <Album_name>Album: God's Country</Album_name>
            <Singer performed_by="Solo">By: Blake Shelton</Singer>
            <Label>Label: Warner Bros. Nashville</Label>Written By:
            <Writers no_of_writer="3">
                <Writer>Devin Dawson</Writer>
                <Writer>Jordan Schmidt</Writer>
                <Writer>Hardy</Writer>
            </Writers>Produced By:
            <Producers no_of_producer="1">
                <Producer>Scott Hendricks</Producer>
            </Producers>Release Year:
            <Release_year> 2019</Release_year>
            <Price>Price: Rs180</Price>
        </Song>
        <Song category="Country" id="CPA9" >
            <Title recorded="American country music">Play It Again</Title>
            <Album_name>Album: Crash My Party</Album_name>
            <Singer performed_by="Solo">By: Luke Bryan</Singer>
            <Label>Label: Capitol Nashville</Label>Written By:
            <Writers no_of_writer="2">
                <Writer>Dallas Davidson</Writer>
                <Writer>Ashley Gorley</Writer>
            </Writers>Produced By:
            <Producers no_of_producer="1">
                <Producer>Jeff Stevens</Producer>
            </Producers>Release Year:
            <Release_year> 2014</Release_year>
            <Price>Price: Rs200</Price>
        </Song>
        <Song category="Pop" id="PBN10">
            <Title>Better Now</Title>
            <Album_name>Album: Beerbongs &amp; Bentleys</Album_name>
            <Singer performed_by="Solo">By: Post Malone</Singer>
            <Label>Label: Republic</Label>Written By:
            <Writers no_of_writer="5">
                <Writer>Post Malone</Writer>
                <Writer>Louis Bell</Writer>
                <Writer>Frank Dukes</Writer>
                <Writer>Billy Walsh</Writer>
                <Writer>Kaan Gunesberk</Writer>
            </Writers>Produced By:
            <Producers no_of_producer="2">
                <Producer>Alfred Lion</Producer>
                <Producer>Louis Bell</Producer>
            </Producers>Release Year:
            <Release_year> 2018</Release_year>
            <Price>Price: Rs280</Price>
        </Song>
        <Song category="Pop" id="PA11">
            <Title>Attention</Title>
            <Album_name>Album: Voicenotes</Album_name>
            <Singer performed_by="Solo">By: Charlie Puth</Singer>
            <Label>Label: Artist Partner, Atlantic</Label>Written By:
            <Writers no_of_writer="2">
                <Writer>Charlie Puth</Writer>
                <Writer>Jacob Kasher</Writer>
            </Writers>Produced By:
            <Producers no_of_producer="1">
                <Producer>Charlie Puth</Producer>
            </Producers>Release Year:
            <Release_year> 2017</Release_year>
            <Price>Price: Rs250</Price>
        </Song>
        <Song category="Pop" id="PDD12">
            <Title recorded="RCA records">Dusk Till Dawn</Title>
            <Album_name>Album: Icarus Falls</Album_name>
            <Singer performed_by="Duo">By: Zayn Malik &amp;Sia</Singer>
            <Label>Label: Republic</Label>Written By:
            <Writers no_of_writer="5">
                <Writer>Zayn Malik</Writer>
                <Writer>Sia Furler</Writer>
                <Writer>Alex Oriet</Writer>
